# Generated by Django 4.2.9 on 2024-07-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_res_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment", old_name="res_id", new_name="res_obj",
        ),
        migrations.AddField(
            model_name="payment",
            name="reserv_id",
            field=models.CharField(default="jaco", max_length=20),
            preserve_default=False,
        ),
    ]
