# Generated by Django 5.0.6 on 2024-05-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='day',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='month',
            field=models.CharField(max_length=30),
        ),
    ]
