# Generated by Django 5.0.6 on 2024-05-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_day_remove_reservation_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='bag_img',
        ),
    ]
