# Generated by Django 5.0.6 on 2024-05-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_bag_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='day',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='hour',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='minute',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='month',
            field=models.IntegerField(),
        ),
    ]
