# Generated by Django 4.2.9 on 2024-06-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0004_reservation_day_reservation_hour_reservation_minute_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reserv_id", models.CharField(default="HaveToMod", max_length=20)),
                ("status", models.IntegerField(default=1)),
                ("status_bull", models.BooleanField(default=False)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.reservation",
                    ),
                ),
            ],
        ),
    ]
