# Generated by Django 4.2.9 on 2024-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_reservstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reserv_id",
            field=models.CharField(default="HaveToMod", max_length=20),
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reservation",
            name="status_bull",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="ReservStatus",),
    ]
