# Generated by Django 4.2.9 on 2024-06-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0006_reservation_reserv_id_reservation_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation", old_name="status_bull", new_name="completed",
        ),
    ]
