# Generated by Django 4.2.9 on 2024-06-24 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_rename_status_bull_reservation_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
