# Generated by Django 4.2.9 on 2024-06-24 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_reservation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
