# Generated by Django 4.2.9 on 2024-06-24 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0012_alter_reservation_date_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
