# Generated by Django 4.2.9 on 2024-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0015_alter_reservation_date_alter_reservation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation", name="date", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserv_id",
            field=models.CharField(default="HaveToMod!!", max_length=20),
        ),
        migrations.AlterField(
            model_name="reservation", name="time", field=models.TextField(),
        ),
    ]
