# Generated by Django 4.2.9 on 2024-07-03 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0017_alter_reservation_date_alter_reservation_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation", old_name="date", new_name="end_date",
        ),
        migrations.RenameField(
            model_name="reservation", old_name="time", new_name="end_time",
        ),
        migrations.RemoveField(model_name="reservation", name="day",),
        migrations.RemoveField(model_name="reservation", name="hour",),
        migrations.RemoveField(model_name="reservation", name="minute",),
        migrations.RemoveField(model_name="reservation", name="month",),
        migrations.AddField(
            model_name="reservation",
            name="bottom",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="shoes",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="top",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
