# Generated by Django 4.2.9 on 2024-07-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0018_rename_date_reservation_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
