# Generated by Django 4.2.9 on 2024-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0020_shoes_alter_reservation_bottom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="shoes",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
