# Generated by Django 4.2.9 on 2024-07-04 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0022_alter_reservation_shoes"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="id",),
        migrations.AddField(
            model_name="reservation", name="cost", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reservation",
            name="location",
            field=models.CharField(default="Seoul", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="desc",
            field=models.TextField(blank=True, default="-"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserv_id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="shoes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoesName",
                to="reservation.shoes",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
