# Generated by Django 4.2.9 on 2024-07-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0023_remove_reservation_id_reservation_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bottom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("amount_s", models.IntegerField()),
                ("amount_m", models.IntegerField()),
                ("amount_L", models.IntegerField()),
                ("amount_XL", models.IntegerField()),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Top",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("amount_s", models.IntegerField()),
                ("amount_m", models.IntegerField()),
                ("amount_L", models.IntegerField()),
                ("amount_XL", models.IntegerField()),
                ("link", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="reservation",
            name="bottom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bottomName",
                to="reservation.bottom",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="top",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topName",
                to="reservation.top",
            ),
        ),
    ]
