# Generated by Django 4.2.9 on 2024-07-05 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0024_bottom_top_alter_reservation_bottom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bottom", name="link", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="bottom", name="name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="bottom",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bottomName",
                to="reservation.bottom",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="shoes",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoesName",
                to="reservation.shoes",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("ST1", "예약 양식 제출 완료"),
                    ("ST2", "예약 완료 및 결제 대기"),
                    ("ST3", "결제 완료"),
                    ("ST4", "배송 중"),
                    ("ST5", "배송 완료"),
                    ("ST6", "반납 완료"),
                    ("ST7", "입고 완료"),
                ],
                default="ST1",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="top",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topName",
                to="reservation.top",
            ),
        ),
        migrations.AlterField(
            model_name="shoes", name="link", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="shoes", name="name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="top", name="link", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="top", name="name", field=models.CharField(max_length=50),
        ),
    ]
