# Generated by Django 4.2.9 on 2024-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0026_item_reservation_etc_alter_reservation_bottom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="F", max_length=1
            ),
            preserve_default=False,
        ),
    ]
