# Generated by Django 4.2.9 on 2024-07-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0027_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="bottom",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "bottom"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bottomName",
                to="reservation.item",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="etc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "etc"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etcName",
                to="reservation.item",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="shoes",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "shoes"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoesName",
                to="reservation.item",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="top",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "top"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topName",
                to="reservation.item",
            ),
        ),
    ]
