# Generated by Django 4.2.9 on 2024-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0028_alter_item_gender_alter_reservation_bottom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
    ]
