# Generated by Django 4.2.9 on 2024-07-08 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0031_alter_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="amount",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("E", "NO Gender"), ("F", "Female"), ("M", "Male")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="model_num",
            field=models.CharField(
                blank=True, max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Others", "free"),
                    (
                        "shoes",
                        (
                            ("220", "220mm"),
                            ("225", "225mm"),
                            ("230", "230mm"),
                            ("235", "235mm"),
                            ("240", "240mm"),
                            ("245", "245mm"),
                            ("250", "250mm"),
                            ("255", "255mm"),
                            ("260", "260mm"),
                            ("265", "265mm"),
                            ("270", "270mm"),
                            ("275", "275mm"),
                            ("280", "280mm"),
                            ("285", "285mm"),
                            ("290", "290mm"),
                            ("295", "295mm"),
                            ("300", "300mm"),
                        ),
                    ),
                    (
                        "top",
                        (
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ),
                    ),
                    (
                        "bottom",
                        (
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ),
                    ),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="bottom",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "bottom"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bottomName",
                to="reservation.item",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="etc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "etc"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etcName",
                to="reservation.item",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="shoes",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "shoes"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoesName",
                to="reservation.item",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="top",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "top"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topName",
                to="reservation.item",
            ),
        ),
    ]
