# Generated by Django 4.2.9 on 2024-07-08 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0032_alter_item_amount_alter_item_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="etc",),
        migrations.AddField(
            model_name="reservation",
            name="bag",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "bag"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bagName",
                to="reservation.item",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Female"), ("E", "NO Gender"), ("M", "Male")],
                max_length=1,
            ),
        ),
    ]
