# Generated by Django 4.2.9 on 2024-07-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0033_remove_reservation_etc_reservation_bag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="contact",
            field=models.CharField(default="lineid", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("E", "NO Gender"), ("F", "Female")],
                max_length=1,
            ),
        ),
    ]
