# Generated by Django 4.2.9 on 2024-07-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0034_reservation_contact_alter_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="contact",
            field=models.CharField(max_length=50),
        ),
    ]
