# Generated by Django 4.2.9 on 2024-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0059_alter_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("E", "NO Gender"), ("F", "Female"), ("M", "Male")],
                max_length=1,
            ),
        ),
    ]
