# Generated by Django 4.2.9 on 2024-07-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0064_alter_item_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="paypal_link",
            field=models.URLField(blank=True),
        ),
    ]
