# Generated by Django 4.2.9 on 2024-07-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0076_alter_item_gender_alter_reservation_paypal_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Female"), ("M", "Male"), ("E", "NO Gender")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="paypal_link",
            field=models.CharField(default="free", max_length=50),
        ),
    ]
