# Generated by Django 4.2.9 on 2024-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0078_alter_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Female"), ("E", "NO Gender"), ("M", "Male")],
                max_length=1,
            ),
        ),
    ]
