# Generated by Django 4.2.9 on 2024-08-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0083_alter_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("E", "NO Gender")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserv_id",
            field=models.CharField(
                default="ste-20240802T004809",
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
