# Generated by Django 4.2.9 on 2024-08-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0084_alter_item_gender_alter_reservation_reserv_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Female"), ("E", "NO Gender"), ("M", "Male")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserv_id",
            field=models.CharField(
                default="ste-20240802T013552",
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
