# Generated by Django 4.2.9 on 2024-08-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0085_alter_item_gender_alter_reservation_reserv_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("E", "NO Gender")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="paypal_link",
            field=models.CharField(default="-", max_length=50),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserv_id",
            field=models.CharField(
                default="Required_pk", max_length=20, primary_key=True, serialize=False
            ),
        ),
    ]
