# Generated by Django 4.2.9 on 2024-08-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0086_alter_item_gender_alter_reservation_paypal_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Female"), ("M", "Male"), ("E", "NO Gender")],
                max_length=1,
            ),
        ),
    ]
