# Generated by Django 4.2.9 on 2024-08-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0087_alter_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("E", "NO Gender"), ("F", "Female"), ("M", "Male")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Others", "free"),
                    (
                        "shoes",
                        (
                            ("220", "220mm"),
                            ("225", "225mm"),
                            ("230", "230mm"),
                            ("235", "235mm"),
                            ("240", "240mm"),
                            ("245", "245mm"),
                            ("250", "250mm"),
                            ("255", "255mm"),
                            ("260", "260mm"),
                            ("265", "265mm"),
                            ("270", "270mm"),
                            ("275", "275mm"),
                            ("280", "280mm"),
                            ("285", "285mm"),
                            ("290", "290mm"),
                            ("295", "295mm"),
                            ("300", "300mm"),
                        ),
                    ),
                    (
                        "top",
                        (
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ),
                    ),
                    (
                        "bottom",
                        (
                            ("XXS", "XXS"),
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("3XL", "3XL"),
                            ("4XL", "4XL"),
                            ("5XL", "5XL"),
                        ),
                    ),
                ],
                max_length=10,
            ),
        ),
    ]
