# Generated by Django 4.2.9 on 2024-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0088_alter_item_gender_alter_item_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("E", "NO Gender"), ("F", "Female")],
                max_length=1,
            ),
        ),
    ]
